### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by emiln**
The README is rather outdated. This pull request should, at its completion:

* Make the introduction more appealing to casual users who don't care about priority lists.
* Explain the new API for the users who do.
* Be a lighter and more entertaining read.

### CODE REVIEW

**Comment by Mikkeren** [comment]
This was sorely needed after the overhaul to the core API and priority lists, and whoever wrote the last version of the README.md should be ashamed.

**Comment by emiln** [comment]
He cried a lot at night.

**Comment by emiln** [comment]
We stil need to document the new API somewhere, though. Whether in the README or a docs folder isn't a big deal to me as long as we do it. Keeping it in the README has the benefit of being glaringly and unavoidably visible whenever we visit the repository, which should help with keeping it updated.

**Comment by Mikkeren** [comment]
I would prefer if we have it in the README, both because it makes it obvious to us when we forget to update it, but also because it lets others find it easily, hopefully encouraging collaboration on the project. (Which I surely expect to happen)

**Pull request merged**
