### PR TITLE
Add combo points to return table of api.Status

### LINKED ISSUE #62: Add ability to query combo points
In anticipation of asking Andy to help me write a feral druid priority list, it seems necessary to be able to query the number of combo points currently amassed by the player. I suggest we add it to the return table of `API.Status()`. It's a pretty simple addition, so the question is mainly where it should reside in the API.

### PR DESCRIPTION
**Pull request by emiln**
This is a simple proposed solution to #62. Closes #62 when merged.

We should probably decide what to do in case you don't have combo points. Do we exclude the table entry entirely, include it with a value like 0, -1, nil, etc.?

### CODE REVIEW

**Comment by emiln** [comment]
A few tasks remain:

- [ ] Decide on return value for classes/forms without combo points.
- [ ] Update documentation.

**Comment by Mikkeren** [comment]
I would suggest that we always have the table entries for these objects, and then return something that clearly suggest that it is invalid, so regular checks on them are likely to explode, to avoid false positives. In this case I would prefer returning -1, as I've done on some of the other numerical values in the API objects.

**Comment by emiln** [comment]
Consistent inclusion is a good approach. The question is then whether we should return -1 (which makes sense for numbers) or nil (which makes sense in a "fail fast" kind of way). -1 might make various checks succeed where you wouldn't want them to, while nil would probably horribly kill the priority list code.

**Comment by Mikkeren** [comment]
Alternatively we can simply return 0, as the in-game function does.
Strictly speaking 0 Combo Points and being unable to gain combo points is not a distinction the API has to handle. If you need combo points for a priority list, you will know.

**Pull request merged**
